@include('adh')

<div class="content" data-scrollview="true">
<div class="container" data-animation="true" data-animation-type="fadeInDown">
<h2 class="content-title">Privacy Notice</h2>
<div class="row">
<div class="col-md-12">
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Introduction</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">1.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This policy applies where we are acting as a data controller with respect to the personal data of our website visitors and service users; in other words, where we determine the purposes and means of the processing of that personal data.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Who are we</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">2.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This website is owned and operated by <em><span style="background-color:yellow">[pennyearner.com]</span></em><span style="background-color:yellow">.</span></span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">2.2&nbsp; &nbsp; &nbsp; You can contact us using our website contact form.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; How we use your personal data</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In this Section 3 we have set out:</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the general categories of personal data that we may process;</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the purposes for which we may process personal data; and</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; the legal bases of the processing.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may process data about your use of our website and services (&quot;<strong>usage data</strong>&quot;). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is our analytics tracking system and Geo IP table. This usage data may be processed for the purposes of analyzing the use of the website and services.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may process your account data (&quot;<strong>account data</strong>&quot;). The account data may include your name and email address. The source of the account data is you. The account data may be processed for the purposes of operating our website, providing our services, ensuring the security of our website and services, maintaining back-ups of our databases and communicating with you.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may process your information included in your personal profile on our website (&quot;<strong>profile data</strong>&quot;). The profile data may include your name, address, telephone number, email address, profile pictures, gender and date of birth. The profile data may be processed for the purposes of enabling and monitoring your use of our website and services. </span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may process your personal data that are provided in the course of the use of our services (&quot;<strong>service data</strong>&quot;). The service data may include your IP logs, activity logs and preferences that you set in the script settings. The source of the service data is you. The service data may be processed for the purposes of operating our website, providing our services, ensuring the security of our website and services, maintaining back-ups of our databases and communicating with you. </span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.6&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may process information relating to transactions, including purchases of goods and services, that you enter into with us and/or through our website (&quot;<strong>transaction data</strong>&quot;). The transaction data may include your contact details, your account name and the transaction details. The transaction data may be processed for the purpose of supplying the purchased goods and services and keeping proper records of those transactions. </span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">3.7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Please do not supply any other person&#39;s personal data to us, unless we prompt you to do so.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Providing your personal data to others</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">4.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Financial transactions relating to our website and services are handled by our payment services providers, <em><span style="background-color:yellow">[identify PSPs]</span></em>. We will share transaction data with our payment services providers only to the extent necessary for the purposes of [processing your payments, refunding such payments and dealing with complaints and queries relating to such payments and refunds]. You can find information about the payment services providers&#39; privacy policies and practices at <em><span style="background-color:yellow">[URLs]</span></em><span style="background-color:yellow">.</span></span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">4.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may disclose your personal data (age, gender and country) to our CPA/GPT Affiliate Network third party suppliers for the purpose of showing you relevant offers and services. Each such third party will act as a data controller in relation to the enquiry data that we supply to it.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; International transfers of your personal data</span></span></strong></span></span></span><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="background-color:yellow"><span style="font-family:&quot;Calibri&quot;,sans-serif">.</span></span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">5.1&nbsp; &nbsp; &nbsp;You acknowledge that [personal data that you submit for publication through our website or services] may be available, via the internet, around the world. We cannot prevent the use (or misuse) of such personal data by others.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Retaining and deleting personal data</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">6.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; This Section 6 sets out our data retention policies and procedure, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">6.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">6.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We will retain your personal data as follows:</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; usage data will be retained for a maximum period of 90 days following the data collection;</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; account data, profile data, service data and transaction data will be retained for a maximum period of 24 hours following your account removal.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">6.4&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Notwithstanding the other provisions of this Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Amendments</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">7.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We may update this policy from time to time by publishing a new version on our website.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">7.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; You should check this page occasionally to ensure you are happy with any changes to this policy.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">8.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; About cookies</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">8.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">8.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cookies do not typically contain any information that personally identifies a user, but personal information that we store about you may be linked to the information stored in and obtained from cookies.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">8.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If you block cookies, you will not be able to use all the features on our website.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">9.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cookies that we use</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">9.1&nbsp;&nbsp;&nbsp; We use cookies for the following purposes:</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; authentication - we use cookies to identify you when you visit our website and as you navigate our website.</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; status - we use cookies to help us to determine if you are logged into our website.</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; personalization - we use cookies to store information about your preferences and to personalize the website for you.</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; security - we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website and services generally.</span></span></span></span></span></p>
<p style="margin-left:60pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">(e)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; analysis - we use cookies to help us to analyze the use and performance of our website and services.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><strong><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">10.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cookies used by our service providers</span></span></strong></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">10.1&nbsp;&nbsp;&nbsp; Our service providers use cookies and those cookies may be stored on your computer when you visit our website.</span></span></span></span></span></p>
<p style="margin-left:30pt; margin-right:0cm; text-align:justify"><span style="font-size:10pt"><span style="font-family:Verdana,sans-serif"><span style="color:black"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">10.2&nbsp;&nbsp;&nbsp; We may use Google Analytics to analyze the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website. Google&#39;s privacy policy is available at: </span></span><a href="https://www.google.com/policies/privacy/"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:blue">https://www.google.com/policies/privacy/</span></span></span></a><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">.</span></span></span></span></span></p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>
<p style="margin-left:0cm; margin-right:0cm; text-align:justify">&nbsp;</p>
</div>
</div>
</div>
</div>
</div>


@include('adf')